[package]
name = "mirvestigator"
version = "0.1.0"
authors = ["Wei-ju Wu <weiju.wu@gmail.com>"]
edition = "2018"

[dependencies]
ftp = "3.0.1"
flate2 = "1.0.7"
itertools = "0.8.0"
json = "0.11.13"
rayon = "1.0.3"
clap = "2.32.0"

[profile.release]
lto = true
